### ISSUE TITLE
ValueError: empty separator

### ISSUE THREAD

**Issue by seanxuu** [InternLM/lagent#101]
command:
```
streamlit run examples/react_web_demo.py  
```
![image](https://github.com/InternLM/lagent/assets/118865326/8e948858-808c-4396-82e2-eb2b333f6948)

Traceback (most recent call last):
  File "Miniconda/envs/internlm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "lagent/examples/react_web_demo.py", line 214, in <module>
    main()
  File "lagent/examples/react_web_demo.py", line 204, in main
    agent_return = st.session_state['chatbot'].chat(user_input)
  File "lagent/agents/react.py", line 224, in chat
    response = self._llm.generate_from_template(prompt, 512)
  File "lagent/lagent/llms/huggingface.py", line 130, in generate_from_template
    return response.split(end_token.strip())[0]
ValueError: empty separator

**_I set my model's path at react_web_demo.py_**
```
    def init_model(self, option):
        """Initialize the model based on the selected option."""
        if option not in st.session_state['model_map']:
            if option.startswith('gpt'):
                st.session_state['model_map'][option] = GPTAPI(
                    model_type=option)
            else:
                st.session_state['model_map'][option] = HFTransformerCasualLM(
                    'models/internlm2-chat-7b')
        return st.session_state['model_map'][option]
```

**Comment by Harold-lkk** [comment]
please update Lagent version and try again
