### ISSUE TITLE
internlm2_agent_cli_demo 运行出错

### ISSUE THREAD

**Issue by xxll88** [InternLM/lagent#154]
![image](https://github.com/InternLM/lagent/assets/54157661/329097d2-9699-4203-bbae-47ef60e769dd)

InternLm2：
首先，我们需要计算复数$z$的共轭$\overline{z}$，然后计算$z$除以$\overline{z}$的乘积减去1的结果。最后，我们将$z$除以这个结果。 Traceback (most recent call last):
  File "/model/code/lagent/examples/internlm2_agent_cli_demo.py", line 110, in <module>
    main()
  File "/model/code/lagent/examples/internlm2_agent_cli_demo.py", line 84, in main
    for agent_return in chatbot.stream_chat(history, max_new_tokens=512):
  File "/model/code/lagent/lagent/agents/internlm2_agent.py", line 290, in stream_chat
    name, language, action = self._protocol.parse(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/model/code/lagent/lagent/agents/internlm2_agent.py", line 166, in parse
    message, code = message.split(
    ^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by liujiangning30** [comment]
请问，用的是什么模型呢？internlm2-chat-7/20b无法复现你遇到的问题

**Comment by Harold-lkk** [comment]
free to reopen the issue if still have the problem
