### ISSUE TITLE
目前GPTAPI不支持internlm api调用吗？

### ISSUE THREAD

**Issue by acwwt** [InternLM/lagent#187]

**Comment by acwwt** [comment]
![PixPin_2024-05-23_17-51-06](https://github.com/InternLM/lagent/assets/110531742/420700b0-11d1-4ceb-9867-b58147b0482a)
我是这样写的，然后运行报错了
```
Traceback (most recent call last):
  File "/root/MetaGPT/demo/demo2.py", line 19, in <module>
    response = chatbot.chat("你好, 你叫什么名字？")
  File "/root/lagent/lagent/agents/internlm2_agent.py", line 234, in chat
    response = self._llm.chat(prompt, **kwargs)
  File "/root/lagent/lagent/llms/openai.py", line 126, in chat
    ret = [task.result() for task in tasks]
  File "/root/lagent/lagent/llms/openai.py", line 126, in <listcomp>
    ret = [task.result() for task in tasks]
  File "/root/.conda/envs/Max-mojo/lib/python3.10/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/root/.conda/envs/Max-mojo/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/root/.conda/envs/Max-mojo/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/lagent/lagent/llms/openai.py", line 217, in _chat
    raise RuntimeError('Calling OpenAI failed after retrying for '
RuntimeError: Calling OpenAI failed after retrying for 2 times. Check the logs for details.
```

**Comment by acwwt** [comment]
我这便测试了一下，GPTAPI的chat是没有问题的，那应该是出现在我agent调用的问题上了
