### ISSUE TITLE
AttributeError: 'GenerationConfig' object has no attribute '_eos_token_tensor'

### ISSUE THREAD

**Issue by jamiechoi1995** [InternLM/lagent#244]
```
Traceback (most recent call last):
  File "/data/anaconda3/envs/torch/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/data/anaconda3/envs/torch/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/data/github/lagent/examples/internlm2_agent_web_demo_hf.py", line 332, in <module>
    main()
  File "/data/github/lagent/examples/internlm2_agent_web_demo_hf.py", line 285, in main
    for agent_return in st.session_state['chatbot'].stream_chat(
  File "/data/anaconda3/envs/torch/lib/python3.11/site-packages/lagent/agents/internlm2_agent.py", line 303, in stream_chat
    for model_state, res, _ in self._llm.stream_chat(prompt, **kwargs):
  File "/data/anaconda3/envs/torch/lib/python3.11/site-packages/lagent/llms/huggingface.py", line 292, in stream_chat
    yield from self.stream_generate(prompt, do_sample, **kwargs)
  File "/data/anaconda3/envs/torch/lib/python3.11/site-packages/lagent/llms/huggingface.py", line 197, in stream_generate
    logits_processor = self.model._get_logits_processor(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/torch/lib/python3.11/site-packages/transformers/generation/utils.py", line 866, in _get_logits_processor
    and generation_config._eos_token_tensor is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GenerationConfig' object has no attribute '_eos_token_tensor'
```

**Comment by EvoNexusX** [comment]
同样的错误

**Comment by Shkklt** [comment]
这个问题有解决么，transformers 4.44.0也会报这个错误
